### ISSUE TITLE
Getting Checksum failures for NLI fever

### ISSUE THREAD

**Issue by waleedkadous** [google-research/true#19]
I'm trying to download the datasets to run evals, but at some point it gets stuck with the following error

```
Traceback (most recent call last):
  File "/home/ray/default/true/src/download_datasets.py", line 403, in <module>
    app.run(main)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ray/default/true/src/download_datasets.py", line 398, in main
    download_fever()
  File "/home/ray/default/true/src/download_datasets.py", line 301, in download_fever
    fever_id_to_label = get_fever_labels()
  File "/home/ray/default/true/src/download_datasets.py", line 292, in get_fever_labels
    fever_data = load_dataset('fever', 'v1.0', split=data_split)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 1702, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/builder.py", line 594, in download_and_prepare
    self._download_and_prepare(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/builder.py", line 665, in _download_and_prepare
    verify_checksums(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/datasets/utils/info_utils.py", line 40, in verify_checksums
    raise NonMatchingChecksumError(error_msg + str(bad_urls))

datasets.utils.info_utils.NonMatchingChecksumError: Checksums didn't match for dataset source files

['https://s3-eu-west-1.amazonaws.com/fever.public/train.jsonl', 'https://s3-eu-west-1.amazonaws.com/fever.public/shared_task_dev.jsonl', 'https://s3-eu-west-1.amazonaws.com/fever.public/shared_task_dev_public.jsonl', 'https://s3-eu-west-1.amazonaws.com/fever.public/shared_task_test.jsonl', 'https://s3-eu-west-1.amazonaws.com/fever.public/paper_dev.jsonl', 'https://s3-eu-west-1.amazonaws.com/fever.public/paper_test.jsonl']
```

**Comment by wintor12** [comment]
Got the same issue. Updating datasets library fixed it.
```pip install -U datasets```

**Comment by roeeaharoni** [comment]
@waleedkadous please let us know if this solves the issue, thanks!
